name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
      
  # php_sniffer:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     # - name: PHP Code Sniffer
  #     #   uses: php-actions/phpcs@v1
  #     #   with:
  #     #     standard: PSR2
  #     #     args: src/

  php_sniffer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer require squizlabs/php_codesniffer --dev
        working-directory: ./src

      - name: PHP Code Beautifier and Fixer
        run: vendor/bin/phpcbf --standard=PSR2 src/
