name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set working directory
        uses: actions/exec@v2
        with:
          command: 'cd src/'

      - name: Install Yarn dependencies
        run: yarn install

      - name: Install Prettier and prettier-plugin-php
        run: yarn add prettier prettier-plugin-php

      - name: Prettify code
        run: yarn prettier --write "**/*.{js,php}"

      
  # php_sniffer:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Change directory to src/
  #       run: cd src/

  #     - name: Composer install
  #       uses: php-actions/composer@v6

  #     - name: PHP Code Sniffer
  #       uses: php-actions/phpcs@v1
  #       with:
  #         php_version: 7.4
  #         path: .  # Maintenant, tu es déjà dans le répertoire src/, donc le point indique le répertoire actuel
  #         standard: phpcs.xml

